// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"base-service/app/comment/job/internal/biz"
	"base-service/app/comment/job/internal/conf"
	"base-service/app/comment/job/internal/data"
	"base-service/app/comment/job/internal/server"
	"base-service/app/comment/job/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	commentRepo := data.NewCommentRepo(dataData, logger)
	commentUsecase := biz.NewCommentUsecase(commentRepo, logger)
	commentJobService := service.NewCommentJobService(commentUsecase, logger, dataData)
	httpServer := server.NewHTTPServer(confServer, commentJobService, logger)
	grpcServer := server.NewGRPCServer(confServer, commentJobService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
