// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"base-service/app/baseapp/interface/internal/biz"
	"base-service/app/baseapp/interface/internal/conf"
	"base-service/app/baseapp/interface/internal/data"
	"base-service/app/baseapp/interface/internal/server"
	"base-service/app/baseapp/interface/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, registry *conf.Registry, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	discovery := data.NewDiscovery(registry)
	commentClient := data.NewCommentServiceClient(confServer, discovery)
	accountClient := data.NewAccountServiceClient(confServer, discovery)
	dataData, cleanup, err := data.NewData(confData, logger, commentClient, accountClient)
	if err != nil {
		return nil, nil, err
	}
	commentRepo := data.NewCommentRepo(dataData, logger)
	accountRepo := data.NewAccountRepo(dataData, logger)
	commentUsecase := biz.NewCommentUsecase(commentRepo, accountRepo, logger)
	accountUsecase := biz.NewAccountUsecase(accountRepo, logger)
	baseappInterfaceService := service.NewBaseappInterfaceService(commentUsecase, accountUsecase, logger)
	httpServer := server.NewHTTPServer(confServer, baseappInterfaceService, logger)
	grpcServer := server.NewGRPCServer(confServer, baseappInterfaceService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
