server:
  http:
    addr: 127.0.0.1:8000
    timeout: 5s
  grpc:
    addr: 127.0.0.1:9000
    timeout: 5s
data:
  database:
    driver: mysql
    source: root:test@123@tcp(127.0.0.1:3306)/comment_service?charset=utf8mb4&parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
registry:
  consul:
    address: 127.0.0.1:8500
    scheme: http