// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsAccountNotFound(err error) bool {
	e := errors.FromError(err)
	return e.Reason == AccountErrorReason_ACCOUNT_NOT_FOUND.String() && e.Code == 404
}

func ErrorAccountNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, AccountErrorReason_ACCOUNT_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

func IsEmailAlreadyUsed(err error) bool {
	e := errors.FromError(err)
	return e.Reason == AccountErrorReason_EMAIL_ALREADY_USED.String() && e.Code == 501
}

func ErrorEmailAlreadyUsed(format string, args ...interface{}) *errors.Error {
	return errors.New(501, AccountErrorReason_EMAIL_ALREADY_USED.String(), fmt.Sprintf(format, args...))
}
